### ISSUE TITLE
Active ICsp connection cause Connect-HPOVMgmt to fail

### ISSUE THREAD

**Issue by susan-ng** [HewlettPackard/POSH-HPICsp#1]
With an active ICsp connection, attempt to connect to OneView 1.20 using the Connect-HPOVMgmt call fails due to the "$global:cimgmtSessionId" variable contains the ICsp connection sessionId.  This results in the error "You are already logged into $Appliance. Please use Disconnect-HPOVMgmt to end your existing session, and then call Connect-HPOVMgmt again."

Following is the response from OneView regarding this issue:-
"ICsp built their library from the HP OneView library, so they need to change the variable and method it uses to check for connection to an appliance. This is not an HP OneView PowerShell library issue."

**Comment by cboeker** [comment]
Updated bindings to remove session conflicts with HP OneView library.

fixed in commit dacbc3fb9e5e4b186116e5ae8f4d224faa8551e3

**Comment by susan-ng** [comment]
Thank you very much for fixing the Connect-HPOVMgmt issue!  OneView is able to create a connection with an active ICsp connection with the HPICsp 1.01 module.  However, the Disconnect-HPICMgmt returns the following failure with the HPICsp 1.01 module.  Please let me know if you would like a new issue submitted for this:

Send-HPICRequest : The remote certificate is invalid according to the validation procedure.
At C:\Users\ng\HPCS\CI\Common\HPICsp\HPICsp.psm1:996 char:9
-         Send-HPICRequest $loginSessionsUri DELETE $global:cimgmtICspSessionId
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-HPICRequest

Disconnect-HPICMgmt : Unable to logoff.  Please verify connectivity to appliance and retry command.

**Comment by cboeker** [comment]
No need for another issue - I've checked in a fix ebbced42a95373741b1cd79771d1259120bd3d6d

**Comment by susan-ng** [comment]
I have verified the Disconnect-HPICMgmt failure no longer occurs with your latest fix.  Thank you very much for fixing this issue!

**Comment by cboeker** [comment]
You are welcome.  Let us know if you come across anything else.
