### ISSUE TITLE
Connect-HPICMgmt fail to create connection when run inside try/catch block

### ISSUE THREAD

**Issue by susan-ng** [HewlettPackard/POSH-HPICsp#2]
The Connect-HPICMgmt function fails to create a connection to the ICsp appliance when it's being run inside a try/catch block.  It returns the error "Cannot bind argument to parameter 'Message' because it is null." when it's being run inside the try/catch block.

**Comment by susan-ng** [comment]
Forgot to mention this issue is reproducible with both the v1.0 and v1.01 HPICsp module.

**Comment by cboeker** [comment]
fixed for 1.01 in commit ad16de47c72db65aeee91888dabad3c7c35f2c24

**Comment by susan-ng** [comment]
I have verified Connect-HPICMgmt no longer fails when being run within the try/catch block.  Thank you so much for your prompt response and for fixing this!

Regards,
Susan

**Comment by cboeker** [comment]
You're welcome, please let us know if you come across anything else
